prep-javascript-conditionals - Lamberto Martinez
Lambpato/prep-0922-code-solutions pull request #14
Opened 2022-09-30 01:24 UTC by Lambpato

<img width="1470" alt="Screen Shot 2022-09-29 at 8 11 07 PM" src="https://user-images.githubusercontent.com/34325124/193169653-41fd9707-4acd-49fa-bcda-8ec9e1911a65.png">

2022-09-30 15:54 UTC, thebearingedge requested changes

2022-09-30 15:54 UTC, thebearingedge commented on prep-javascript-conditionals/index.html
> +    if (dayOfTheWeek === ('saturday' || dayOfTheWeek === 'sunday')) {
You'll want to remove the inner parentheses here so that your variable isn't always compared to `"saturday"`

2022-09-30 18:54 UTC, Lambpato commented on prep-javascript-conditionals/index.html
> +    if (dayOfTheWeek === ('saturday' || dayOfTheWeek === 'sunday')) {
<img width="1470" alt="Screen Shot 2022-09-30 at 1 53 50 PM" src="https://user-images.githubusercontent.com/34325124/193337765-bbc34a08-b67c-4071-9e8f-63c7b511c427.png">

2022-10-01 17:38 UTC, Lambpato commented
<img width="1470" alt="Screen Shot 2022-10-01 at 12 35 48 PM" src="https://user-images.githubusercontent.com/34325124/193421484-5186428e-0ccd-43e8-a2a8-3496cb3760cb.png">

2022-10-01 18:21 UTC, thebearingedge approved these changes

2022-10-01 18:35 UTC, merged