prep-css-display - Lamberto Martinez
Lambpato/prep-0922-code-solutions pull request #7
Opened 2022-09-24 09:54 UTC by Lambpato

2022-09-24 09:55 UTC, Lambpato commented
![Uploading Screen Shot 2022-09-24 at 2.45.52 AM.png…]()

2022-09-24 14:57 UTC, thebearingedge requested changes
Hi Lamberto, looks like your screenshots didn't upload. When you have a moment, please add your screenshot and shoot me a DM on slack 👍

2022-09-26 20:33 UTC, Lambpato commented
<img width="1470" alt="Screen Shot 2022-09-25 at 3 35 14 AM" src="https://user-images.githubusercontent.com/34325124/192374510-86a92149-63a5-40b7-b609-138162893e75.png">

2022-09-27 16:23 UTC, thebearingedge approved these changes

2022-09-27 19:01 UTC, merged